### ISSUE TITLE
Swedbank store certificate problem

### ISSUE THREAD

**Issue by josla972** [samuellb/fribid#10]
I get an error message complaining about hostname mismatch. file = (null) and request = internet.swedbank.se . Even after fixing the free-call (see pull request), origin/file is still (null). Hardcoding origin = "internet.swedbank.se" fixes the problem for me, but that is no long term solution. Tell me if you need debug help if you do not have swedbank or the same issue.

**Comment by samuellb** [comment]
Well I have swedbank but last time i tried I think I got "internetbank.swedbank.se" for both. Anyway, "file = (null)" looks like a bug by itself. Do you perhaps have any old certificates lying around (in ~/cbt)? Did you get a new certificate file in ~/cbt ?

**Comment by josla972** [comment]
Yes, I do have a couple of old certificates lying around. Perhaps I should remove them? Yes, I got a new certificate everytime, although unusable ones until I hardcoded the url in origin and reran the procedure.

**Comment by samuellb** [comment]
Closing this issue because it's related to the old BankID protocol which is no longer used
