### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by josla972** [samuellb/fribid#5]
Using Firefox 24.2 and the stable release of fribid. Built from source for Gentoo Linux x86_64. 

I can't seem to get it to work on sites that worked before (e.g. skatteverket). I do not have more information than this right now, but I'll gladly help you with debugging.

**Comment by samuellb** [comment]
I'm quite busy right now but I'll have a look at it after the new years eve.

Also, there's a known bug with IPv6 in the stable release with Skatteverket. So if you're using IPv6 then please try the GIT master branch.

**Comment by KristianKarl-zz** [comment]
I just tested it, and it worked for me without any problems. This is what I did on my Fedora 20 machine:
1) Building it:
git clone https://github.com/samuellb/fribid.git
cd fribid
./configure --disable-pkcs11
make && su -c 'make install'

2) Copied my .p12 file to folder ~/cbt
3) Started Firefox [version 26.0] and logged in at skatteverket.se using BankID, with no problems

**Comment by josla972** [comment]
Did 1) and 2) and used Firefox 24.2 and no BankID software is found on pages that used to work. test.bankid.com complains that it does not support 64-bit Linux.

**Comment by josla972** [comment]
An update: It seems to work with Epiphany, so it is probably some kind of Firefox issue.

**Comment by KristianKarl-zz** [comment]
There's sometimes issues with the file: <strong>~/.config/fribid/expiry</strong>
In my case, it prevents me from logging in to Skandiabanken saying that I don't have a correct version of BankID: "Versionskontroll av BankID säkerhetsprogram
BankID säkerhetsprogram måste versionskontrolleras och eventuellt uppgraderas."

My [~/.config/fribid/expiry] looks like this per default:

<pre>[expiry]
best-before=1390790655
still-valid=true
version-to-emulate=4.15.0.14
checked-with-version=2</pre>

Changing following line fixes the problem at Skandiabanken for me: 

<pre>version-to-emulate=4.19.1.11663</pre>

**Comment by josla972** [comment]
I found the issue! Normally, the fribid plugin is installed into /usr/lib/mozilla/plugins/libfribidplugin.so. On my machine however, most plugins for firefox seem to be situated in /usr/lib/nsbrowser/plugins. I copied the symlink there and voila, it works in firefox again!
