### ISSUE TITLE
Didn't build... because..

### ISSUE THREAD

**Issue by shellkr** [samuellb/fribid#6]
Couldn't get it to build until I noticed in /doc/Makefile..

> Test scripts
> install -d $(DOCDIR)/fribid
> install -d $(DOCDIR)/fribid/examples
> ...

So changed to..

> Test scripts
> install -d $(DESTDIR)$(DOCDIR)/fribid
> install -d $(DESTDIR)$(DOCDIR)/fribid/examples
> ...

And got it working..

**Comment by samuellb** [comment]
Thanks, committed and pushed now! :)
